language: php

sudo: false

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

env:
  global:
    - setup=basic
    - coverage=no
  matrix:
    - laravel=5.6.*
    - laravel=5.7.*
    - laravel=dev-master

before_script:
  - composer config discard-changes true
  - if [[ $setup = 'basic' ]]; then travis_retry composer require "laravel/framework=${laravel}" --prefer-dist --no-interaction; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer require "laravel/framework=${laravel}" --prefer-dist --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer require "laravel/framework=${laravel}" --prefer-dist --no-interaction --prefer-lowest --prefer-stable; fi
  - if [[ $setup = 'coveralls' ]]; then travis_retry composer require "laravel/framework=${laravel}" "php-coveralls/php-coveralls=^2.1" --prefer-dist --no-interaction --dev; fi

script:
  - if [[ $coverage = 'yes' ]]; then vendor/bin/phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml; fi
  - if [[ $coverage = 'no' ]]; then vendor/bin/phpunit -c phpunit.xml; fi

after_script:
  - if [[ $setup = 'coveralls' ]]; then php vendor/bin/php-coveralls -v; fi

matrix:
  include:
    - php: 7.1
      env:
        - setup=lowest
        - laravel=5.6.*
    - php: 7.1
      env:
        - setup=basic
        - laravel=5.6.*
    - php: 7.1
      env:
        - setup=stable
        - laravel=5.6.*
    - php: 7.1
      env:
        - setup=lowest
        - laravel=5.7.*
    - php: 7.1
      env:
        - setup=basic
        - laravel=5.7.*
    - php: 7.1
      env:
        - setup=stable
        - laravel=5.7.*
    - php: 7.1
      env: setup=coveralls coverage=yes laravel=5.6.*
  allow_failures:
    - env: laravel=dev-master
    - env: setup=coveralls coverage=yes laravel=5.6.*
  fast_finish: true
