language: php

sudo: false

php:
  - 7.0
  - 7.1

env:
  global:
    - setup=basic
    - coverage=no
  matrix:
    - laravel=5.4.*
    - laravel=5.5.*

before_script:
  - composer config discard-changes true
  - if [[ $setup = 'basic' ]]; then travis_retry composer require "laravel/framework=${laravel}" --prefer-dist --no-interaction; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer require "laravel/framework=${laravel}" --prefer-dist --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer require "laravel/framework=${laravel}" --prefer-dist --no-interaction --prefer-lowest --prefer-stable; fi

script:
  - ./vendor/bin/phpunit -c phpunit.xml

matrix:
  include:
    - php: 7.0
      env:
        - setup=lowest
        - laravel=5.4.*
    - php: 7.0
      env:
        - setup=stable
        - laravel=5.4.*
  allow_failures:
    - env: setup=lowest
    - env: laravel=5.5.*
  fast_finish: true
